# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: bitriseio/docker-android

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test


#
# Build configuration for Circle CI
#

general:
    artifacts:
        - ~/cities/app/build/outputs/apk/

machine:
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

test:
    override:
        # start the build
        - (./gradlew assemble):
            timeout: 360
        # start the emulator
        - emulator -avd circleci-android22 -no-audio -no-window:
            background: true
            parallel: true
        # wait for it to have booted
        - circle-android wait-for-boot
        # unlock the emulator screen
        - sleep 30
        - adb shell input keyevent 82
        # run tests  against the emulator.
        - ./gradlew connectedDevelopmentDebugAndroidTest -PdisablePreDex
        # copy the build outputs to artifacts
        - cp -r app/build/outputs $CIRCLE_ARTIFACTS
        # copy the test results to the test results directory.
        - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS



